apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: opsapp
  name: opsapp
  namespace: app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opsapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opsapp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: failure-domain.beta.kubernetes.io/region
                operator: In
                values:
                - us-east-1
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: safeem/opstree:1.5
        name: opstree
        command:
        - "catalina.sh"
        - "run"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
status: {}
