apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opsapp
  name: opsapp
  namespace: app-dev
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: opsapp
  type: NodePort
status:
  loadBalancer: {}
