apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-client
  name: mysql-client
spec:
  containers:
  - image: ubuntu
    name: mysql-client
    command:
    - /bin/bash
    - -c
    - sleep 60000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
